### ISSUE TITLE
Document How to Specify Unique Persistent MAC addresses for VMs using Bridge

### ISSUE THREAD

**Issue by erwin** [quickemu-project/quickemu#287]
Persistent MACs may be [out of scope for the project](https://github.com/quickemu-project/quickemu/issues/48#issuecomment-914301590_
), so I at least wanted to share some simple instructions in case anyone else wants to do this:

> While network bridging is a great feature it is out of scope for quickemu, which is designed to be a means of taking your VMs with you on USB drive and just work on any Linux without configuration

First off, both `./quickemu` and `./quickget` and bash shell scripts. They're very clearly written, so if you want to make any of your own changes, it should be quite easy.

When you're using a bridged network interface to connect your VM to your network, each VM must have it's own MAC address. If you don't explicitly set this MAC address, you'll have multiple VMs sending the same MAC, and you'll be loosing packets when you run two VMs at the same time (that will try to share both the MAC address, and then the IP).

You really just need to edit one line to add `mac` (for MAC address) when using a bridged interface.

```diff
diff --git a/quickemu b/quickemu
index 5507580..55fb23a 100755
--- a/quickemu
+++ b/quickemu
@@ -871,7 +871,7 @@ function vm_boot() {
   if [ -n "${bridge}" ]; then
     # Enable bridge mode networking
     # shellcheck disable=SC2054,SC2206
-    args+=(-nic bridge,br=${bridge},model=virtio-net-pci)
+    args+=(-nic bridge,br=${bridge},model=virtio-net-pci,mac=${macaddr})
   else
     # shellcheck disable=SC2054,SC2206
     args+=(-device ${NET_DEVICE},netdev=nic -netdev ${NET},id=nic)
@@ -1027,6 +1027,7 @@ function display_param_check() {
 # Lowercase variables are used in the VM config file only
 boot="efi"
 bridge=""
+macaddr=""
 cpu_cores=""
 disk_img=""
 disk_size=""
```

Then in your `.conf` file for each VM, you'll want to specify both the `bridge` and `macaddr`.

```bash
guest_os="freebsd"
disk_img="freebsd-13.0/disk.qcow2"
iso="freebsd-13.0/FreeBSD-13.0-RELEASE-amd64-dvd1.iso"
bridge="br0"
macaddr="52:54:00:AB:51:AE"
```

Note that qemu requires that the Mac address is in the range:
`52:54:00:AB:00:00` - `52:54:00:AB:FF:FF`, so you can generate your own randomish MAC addresses with:

```bash
printf '52:54:00:AB:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256))
```

That's basically all that's required ONCE YOU'VE ALREADY GOT THE BRIDGE WORKING... These notes are ONLY about helping once you've already got the bridge working. To get the bridge itself up, if your system supports netplan, assuming your primary network interface is `eno1`, you would want to create `/etc/netplan/01-netplan.yaml`

```yaml
---
network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false
    wlp4s0:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:
      interfaces: [eno1]
      addresses: [192.168.0.10/24]
      routes:
        - to: default
          via: 192.168.0.1
      mtu: 1500
      nameservers:
        addresses: [192.168.0.1]
      parameters:
        stp: false
        forward-delay: 0
      dhcp4: false
      dhcp6: false
```

Then run:

```
sudo netplan generate
sudo netplan --debug apply
```

Best of luck.
